name: CAPB Welcome Bot
on:
  pull_request:
    types: [opened]

jobs:
  welcome-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Post Welcome Message
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hello! I am captcha-both bot. 

              In the meantime, if you are applying for a recommendation, please make sure you didn't do your recommendation in your own name or your recommendations will not be approved. Make sure it's the same as the original one, but it has your recommendations. If not, then your recommendation will be cancelled and you will have to make another PR.

              **If you are applying to be a member:**
              Please make sure you have the requirements. 

              **Requirements:**
              - You need to have an Email OR a Phone Number. 
              - If you don't have an email or phone number, your application will be rejected. 
              - You don't need both, but you at least need one.

              **To Submit:**
              1. You must be nice, professional, and unique.
              2. Submit an online paper saying your Name, Email or Phone (choose one), What you can do, and Why you want to become a member.
              3. **IMPORTANT:** You have to PIN that attachment to the PR. If I cannot see the attachment, your PR will be closed.

              *Please wait a while. It might take a couple of days, weeks, or even a month because our team is really small. We don't have that many members yet.* **Note:** Being a member is free!`
            })
